  version: '3.8'

  services:
    db:
      image: postgres:15
      container_name: atividades_postgres
      environment:
        POSTGRES_DB: AtividadesBD
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: atividades_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin123
      ports:
        - "5050:80"
      depends_on:
        - db

  volumes:
    postgres_data:
